### ISSUE TITLE
No releases available on github.

### ISSUE THREAD

**Issue by jieter** [kadaster/nlmaps#3]
https://nlmaps.nl/docs.html mentions:

> Finally, you will need the nlmaps library itself, which you can download from the latest release on Github.

But there are [no releases](https://github.com/kadaster/nlmaps/releases) when I follow the link.

**Comment by hpfast** [comment]
@jieter until this gets fixed the relevant files can be found in the `dist` directory.

**Comment by nlmapsteam** [comment]
Releases are available now.
