### ISSUE TITLE
Support www. prefix for nlmaps.nl url

### ISSUE THREAD

**Issue by jieter** [kadaster/nlmaps#5]
Currently, looking up `www.nlmaps.nl` doesn't work:

```
$ nslookup www.nlmaps.nl
Server:		127.0.1.1
Address:	127.0.1.1#53

** server can't find www.nlmaps.nl: NXDOMAIN
```
the [twitter link](https://twitter.com/webmappery/status/880312743173246980) points to www.nlmaps.nl too, so might be worthwhile to add an alias for the `www` subdomain.

**Comment by nlmapsteam** [comment]
The www subdomain has been requested and should be available in the next few days.

**Comment by jieter** [comment]
This is fixed too.
