### ISSUE TITLE
Problem building nlmaps

### ISSUE THREAD

**Issue by geoloep** [kadaster/nlmaps#6]
I tried to build nlmaps on my local machine but keep running into the same problem during the running of the build-all script:

> /nlmaps/node_modules/browser-resolve/node_modules/resolve/lib/async.js:187
                if (n) return cb(null, n, pkg);
> 
>TypeError: Cannot read property 'existsSync' of undefined

This results in the "asyncGenerator" missing from the bundles. (Though I wonder were it is used). It looks like a problem in the code of a dependency but I cannot figure out how to avoid it. Perhaps my build environment is not set up properly, but there is no information on specific requirements in the docs of this project. Would love to hear where it's going wrong.

**Comment by hpfast** [comment]
I recognize this issue. I haven't been able to track it precisely but if I remember correctly it has to do with the build/liveserver setup, not any actual code used in the project (as you figured out yourself already). So I think you can ignore it safely for now.

**Comment by geoloep** [comment]
Upon further inspection this error seems to prevent the building of the packages nlmaps-leaflet and nlmaps. Perhaps the missing "asyncGenerator" was unrelated. I noticed this after trying to build changes in the nlmaps-leaflet package.

**Comment by geoloep** [comment]
I seem to have resolved this issue, though I ran into some other problems. Will close for now.
